### ISSUE TITLE
Commit 57ae270 breaks compilation with disable-debug flag

### ISSUE THREAD

**Issue by atoppi** [sctplab/usrsctp#484]
We found out a compilation error when using `--disable-debug` flag in recent usrsctp versions.
```bash
./bootstrap
./configure --prefix=/usr --disable-static --disable-debug --disable-programs
make -j$(nproc)
```
**Output**
```bash
user_environment.c: In function ‘init_random’:
user_environment.c:102:8: error: implicit declaration of function ‘SCTP_GETTIME_TIMEVAL’ [-Werror=implicit-function-declaration]
  102 |  (void)SCTP_GETTIME_TIMEVAL(&now);
      |        ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

Removing `--disable-debug` make the issue disappear.

**git bisect**
```bash
57ae270ea93aa7ee00f97376344f1a642fc4d638 is the first bad commit
commit 57ae270ea93aa7ee00f97376344f1a642fc4d638
Author: Michael Tuexen <tuexen@fh-muenster.de>
Date:   Sun Jun 14 16:47:42 2020 +0200

    Improve the initialization of the random number generator
    on platforms not providing arc4random_buf().
    
    Thanks to Natalie Silvanovich of Google Project Zero for
    finding and reporting the issue.
```

**Comment by tuexen** [comment]
Should be fixed by https://github.com/sctplab/usrsctp/issues/484. Thanks for reporting!
