### ISSUE TITLE
user_mbuf.h:223:30: error: '*mret.m_hdr.mh_flags' may be used uninitialized

### ISSUE THREAD

**Issue by Ri0n** [sctplab/usrsctp#586]
```
In file included from /home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:44:
In function 'm_move_pkthdr',
    inlined from 'm_prepend' at /home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:1333:3:
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.h:223:30: error: '*mret.m_hdr.mh_flags' may be used uninitialized [-Werror=maybe-uninitialized]
  223 | #define m_flags         m_hdr.mh_flags
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:824:60: note: in expansion of macro 'm_flags'
  824 |         to->m_flags = (from->m_flags & M_COPYFLAGS) | (to->m_flags & M_EXT);
      |                                                            ^~~~~~~
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c: In function 'm_prepend':
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.h:223:30: error: '*mret.m_hdr.mh_flags' may be used uninitialized [-Werror=maybe-uninitialized]
  223 | #define m_flags         m_hdr.mh_flags
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:1336:16: note: in expansion of macro 'm_flags'
 1336 |         if (m->m_flags & M_PKTHDR) {
      |                ^~~~~~~
HEAD is now at 8f98d9b7 Avoid maybe uninitialized warning at least with gcc
In function 'm_dup1',
    inlined from 'm_pulldown' at /home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:990:7:
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.h:221:30: error: '*mret.m_hdr.mh_data' may be used uninitialized [-Werror=maybe-uninitialized]
  221 | #define m_data          m_hdr.mh_data
      |                              ^
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.h:96:35: note: in expansion of macro 'm_data'
   96 | #define mtod(m, t)      ((t)((m)->m_data))
      |                                   ^~~~~~
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:926:33: note: in expansion of macro 'mtod'
  926 |         m_copydata(m, off, len, mtod(n, caddr_t));
      |                                 ^~~~
In function 'm_dup_pkthdr',
    inlined from 'm_dup1' at /home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:922:18,
    inlined from 'm_pulldown' at /home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:990:7:
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.h:223:30: error: '*mret.m_hdr.mh_flags' may be used uninitialized [-Werror=maybe-uninitialized]
  223 | #define m_flags         m_hdr.mh_flags
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:1218:60: note: in expansion of macro 'm_flags'
 1218 |         to->m_flags = (from->m_flags & M_COPYFLAGS) | (to->m_flags & M_EXT);
      |                                                            ^~~~~~~
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c: In function 'm_pulldown':
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.h:221:30: error: '*mret.m_hdr.mh_data' may be used uninitialized [-Werror=maybe-uninitialized]
  221 | #define m_data          m_hdr.mh_data
      |                              ^
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.h:96:35: note: in expansion of macro 'm_data'
   96 | #define mtod(m, t)      ((t)((m)->m_data))
      |                                   ^~~~~~
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:1058:16: note: in expansion of macro 'mtod'
 1058 |         memcpy(mtod(o, caddr_t), mtod(n, caddr_t) + off, hlen);
      |                ^~~~
[ 19%] No patch step for 'QcaProject'
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c: In function 'm_split':
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.h:393:21: error: '*mret.m_hdr.mh_data' may be used uninitialized [-Werror=maybe-uninitialized]
  393 |         (m)->m_data += (MLEN - (len)) & ~(sizeof(long) - 1);            \
      |                     ^~
/home/rion/temp/build/iris/usrsctp/src/UsrSCTPProject/usrsctplib/user_mbuf.c:1531:17: note: in expansion of macro 'M_ALIGN'
 1531 |                 M_ALIGN(n, remain);
      |                 ^~~~~~~
```

build on Gentoo Linux with GCC 11.1.0.

```
cmake -DBUILD_SHARED_LIBS=OFF -Dsctp_build_programs=OFF -Dsctp_build_shared_lib=OFF -Dsctp_debug=OFF -Dsctp_inet=OFF -Dsctp_inet6=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
```

**Comment by Neustradamus** [comment]
@tuexen: What do you think?

**Comment by tuexen** [comment]
I think all of them a false positives.

**Comment by Ri0n** [comment]
I agree about the false positives. I also noticed the option to disable Werror via cmake option. Just migrated to it. Maybe it's better to disable Werror by default if there is no way to avoid the warnings.  Or at least just silent maybe-uninitialized for user_mbuf. A report to gcc would be nice to have too.

Another way to fix the issue I guess is to simplify pointers magic around allocating mbufs.
