### PR TITLE
meson: Fix sconn_len detection (#411)

### PR DESCRIPTION
**Pull request by aleb**
have_sconn_len was always false because compiler.has_member generates a C file
which does not build because the compiler can't include "usrsctp.h". Fixed by
specifying the include path.

### CODE REVIEW

**Comment by aleb** [comment]
Note, the mac build fails now with:

```
$ cd mb1
✓  ab@Alexandrus-MacBook  2019-12-15 01:58  /Users/ab/p/usrsctp/mb1   (git)-[mac]- 
$ ninja      
[25/91] Compiling C object 'ekr_loop_upcall@exe/programs_ekr_loop_upcall.c.o'.
FAILED: ekr_loop_upcall@exe/programs_ekr_loop_upcall.c.o 
cc -Iekr_loop_upcall@exe -I. -I.. -Iusrsctplib -I../usrsctplib -Iusrsctplib/netinet -I../usrsctplib/netinet -Iusrsctplib/netinet6 -I../usrsctplib/netinet6 -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -std=c99 -g -pedantic -Wall -Wextra -Wfloat-equal -Wshadow -Wpointer-arith -Winit-self -Wno-unused-function -Wno-unused-parameter -Wno-unreachable-code -Wstrict-prototypes -D__Userspace__ -DSCTP_SIMPLE_ALLOCATOR -DSCTP_PROCESS_LEVEL_LOCKS -D__Userspace_os_Darwin -U__APPLE__ -D__APPLE_USE_RFC_2292 -Wno-address-of-packed-member -Wno-deprecated-declarations -DHAVE_SYS_QUEUE_H -DHAVE_NETINET_IP_ICMP_H -DHAVE_STDATOMIC_H -DHAVE_SA_LEN -DHAVE_SIN_LEN -DHAVE_SIN6_LEN -DHAVE_SCONN_LEN -DINET -DINET6 -MD -MQ 'ekr_loop_upcall@exe/programs_ekr_loop_upcall.c.o' -MF 'ekr_loop_upcall@exe/programs_ekr_loop_upcall.c.o.d' -o 'ekr_loop_upcall@exe/programs_ekr_loop_upcall.c.o' -c ../programs/ekr_loop_upcall.c
../programs/ekr_loop_upcall.c:483:8: error: no member named 'sconn_len' in 'struct sockaddr_conn'
        sconn.sconn_len = sizeof(struct sockaddr_conn);
        ~~~~~ ^
../programs/ekr_loop_upcall.c:495:8: error: no member named 'sconn_len' in 'struct sockaddr_conn'
        sconn.sconn_len = sizeof(struct sockaddr_conn);
        ~~~~~ ^
../programs/ekr_loop_upcall.c:512:8: error: no member named 'sconn_len' in 'struct sockaddr_conn'
        sconn.sconn_len = sizeof(struct sockaddr_conn);
        ~~~~~ ^
3 errors generated.
[30/91] Compiling C object 'usrsctp@sha/usrsctplib_netinet_sctp_output.c.o'.
ninja: build stopped: subcommand failed.
```

**Comment by lgrahl** [comment]
This is probably an oversight from my side. Can't comment on how to fix `-U__APPLE__` other than that this seems like a hack to me (and I just adopted it from the CMake files).

**Comment by tuexen** [comment]
One has to use two different sets of compile flags. One should be used for compiling the library and it must include `-U__APPLE__`. The other one is used for everything else and it must not include `-U__APPLE__`.

The test whether `HAVE_SCONN_LEN` has to be defined or not, must be based on testing the `struct sockaddr_conn` from `usrsctp.h` WITHOUT using `-U__APPLE__`. That is the way it is done using the autotools.
@weinrank Is this also the way it is done using cmake?

**Comment by aleb** [comment]
Running `bootstrap && ./configure` prints:
```
checking for struct sockaddr_conn.sconn_len... yes
```

Same as the meson output:
```
Checking whether type "struct sockaddr_conn" has member "sconn_len" : YES 
```

So this commit is correct. Ok to merge it like this and fix the meson build separately?
Or is there an easy fix I can add?

**Comment by tuexen** [comment]
I think this fix is OK. @lgrahl Any idea how to fix the build?

**Comment by aleb** [comment]
Below are the commands used to build `ekr_loop_upcall.c`:

meson:

> cc -Iekr_loop_upcall@exe -I. -I.. -Iusrsctplib -I../usrsctplib -Iusrsctplib/netinet -I../usrsctplib/netinet -Iusrsctplib/netinet6 -I../usrsctplib/netinet6 -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -std=c99 -g -pedantic -Wall -Wextra -Wfloat-equal -Wshadow -Wpointer-arith -Winit-self -Wno-unused-function -Wno-unused-parameter -Wno-unreachable-code -Wstrict-prototypes -D__Userspace__ -DSCTP_SIMPLE_ALLOCATOR -DSCTP_PROCESS_LEVEL_LOCKS -D__Userspace_os_Darwin -U__APPLE__ -D__APPLE_USE_RFC_2292 -Wno-address-of-packed-member -Wno-deprecated-declarations -DHAVE_SYS_QUEUE_H -DHAVE_NETINET_IP_ICMP_H -DHAVE_STDATOMIC_H -DHAVE_SA_LEN -DHAVE_SIN_LEN -DHAVE_SIN6_LEN -DHAVE_SCONN_LEN -DINET -DINET6 -MD -MQ 'ekr_loop_upcall@exe/programs_ekr_loop_upcall.c.o' -MF 'ekr_loop_upcall@exe/programs_ekr_loop_upcall.c.o.d' -o 'ekr_loop_upcall@exe/programs_ekr_loop_upcall.c.o' -c ../programs/ekr_loop_upcall.c



autotools:

> gcc -DPACKAGE_NAME=\"libusrsctp\" -DPACKAGE_TARNAME=\"libusrsctp\" -DPACKAGE_VERSION=\"0.9.3.0\" -DPACKAGE_STRING=\"libusrsctp\ 0.9.3.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libusrsctp\" -DVERSION=\"0.9.3.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSCTP_DEBUG=1 -DINET=1 -DINET6=1 -DHAVE_SOCKET=1 -DHAVE_INET_ADDR=1 -DHAVE_STDATOMIC_H=1 -DHAVE_SYS_QUEUE_H=1 -DHAVE_NETINET_IP_ICMP_H=1 -DHAVE_SA_LEN=1 -DHAVE_SIN_LEN=1 -DHAVE_SIN6_LEN=1 -DHAVE_SCONN_LEN=1 -I.  -I./../usrsctplib   -g -O2 -std=c99 -Wno-deprecated-declarations -D__APPLE_USE_RFC_2292 -pedantic -Wall -Werror -g -O0 -MT ekr_loop_upcall.o -MD -MP -MF .deps/ekr_loop_upcall.Tpo -c -o ekr_loop_upcall.o ekr_loop_upcall.c


cmake:

> [ 89%] Building C object programs/CMakeFiles/ekr_loop_upcall.dir/ekr_loop_upcall.c.o
cd /Users/ab/p/usrsctp/cm1/programs && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DHAVE_NETINET_IP_ICMP_H -DHAVE_SA_LEN -DHAVE_SCONN_LEN -DHAVE_SIN6_LEN -DHAVE_SIN_LEN -DHAVE_STDATOMIC_H -DHAVE_SYS_QUEUE_H -DINET -DINET6 -DSCTP_DEBUG -D__APPLE_USE_RFC_2292 -I/Users/ab/p/usrsctp/usrsctplib  -std=c99 -pedantic -Wall -Wextra -Wfloat-equal -Wshadow -Wpointer-arith -Wunreachable-code -Winit-self -Wno-unused-function -Wno-unused-parameter -Wno-unreachable-code -Wstrict-prototypes -Werror -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk   -o CMakeFiles/ekr_loop_upcall.dir/ekr_loop_upcall.c.o   -c /Users/ab/p/usrsctp/programs/ekr_loop_upcall.c

> [ 91%] Linking C executable ekr_loop_upcall
cd /Users/ab/p/usrsctp/cm1/programs && /usr/local/Cellar/cmake/3.15.3/bin/cmake -E cmake_link_script CMakeFiles/ekr_loop_upcall.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -std=c99 -pedantic -Wall -Wextra -Wfloat-equal -Wshadow -Wpointer-arith -Wunreachable-code -Winit-self -Wno-unused-function -Wno-unused-parameter -Wno-unreachable-code -Wstrict-prototypes -Werror -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/ekr_loop_upcall.dir/ekr_loop_upcall.c.o CMakeFiles/ekr_loop_upcall.dir/programs_helper.c.o  -o ekr_loop_upcall -Wl,-rpath,/Users/ab/p/usrsctp/cm1/usrsctplib ../usrsctplib/libusrsctp.1.0.0.dylib

**Comment by aleb** [comment]
`__APPLE__` is used all over the place in /usrsctplib. Should that be replaced with `__APPLE_USE_RFC_2292`?

**Comment by aleb** [comment]
ping

**Comment by tuexen** [comment]
`__APPLE__` is used to specify code for the Mac OS kernel implementation. That is why we do the `-U__APPLE_` dance... But only for building the library. So your fix is correct.

@grahl: OK to commit this?

**Comment by aleb** [comment]
I moved the `-U__APPLE__` arg from the project arguments to the library target arguments
https://mesonbuild.com/Adding-arguments.html#project-arguments

**Comment by tuexen** [comment]
Thanks a lot for the patch!

**Comment by lgrahl** [comment]
Sorry for the late response. Yeah, I wasn't sure how to that *dance* but the result looks good to me now.
