### ISSUE TITLE
build failes with gcc 7.1.1

### ISSUE THREAD

**Issue by stfl** [sctplab/usrsctp#149]
I am trying to build on Manjaro Arch Linux,
Linux stefan-pc 4.10.17-2-MANJARO #1 SMP PREEMPT Sun May 21 11:02:41 UTC 2017 x86_64 GNU/Linux

it works with gcc-5 (5.4.0)

```
Scanning dependencies of target usrsctp-static
[  2%] Building C object CMakeFiles/usrsctp-static.dir/netinet6/sctp6_usrreq.c.o
[  4%] Building C object CMakeFiles/usrsctp-static.dir/netinet/sctp_callout.c.o
[  6%] Building C object CMakeFiles/usrsctp-static.dir/netinet/sctp_input.c.o
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c: In function ‘sctp_process_control’:
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:4825:38: error: ‘%s’ directive output truncated writing 74 bytes into a region of size 58 [-Werror=format-truncation=]
    snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
                                      ^~            ~~~~~~~~
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:4825:4: note: ‘snprintf’ output 110 bytes into a destination of size 64
    snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:4871:39: error: ‘%s’ directive output truncated writing 74 bytes into a region of size 58 [-Werror=format-truncation=]
     snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
                                       ^~            ~~~~~~~~
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:4871:5: note: ‘snprintf’ output 110 bytes into a destination of size 64
     snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c: In function ‘sctp_common_input_processing’:
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:6017:38: error: ‘%s’ directive output truncated writing 74 bytes into a region of size 58 [-Werror=format-truncation=]
    snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
                                      ^~            ~~~~~~~~
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:6017:4: note: ‘snprintf’ output 118 bytes into a destination of size 64
    snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:6082:38: error: ‘%s’ directive output truncated writing 74 bytes into a region of size 58 [-Werror=format-truncation=]
    snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
                                      ^~            ~~~~~~~~
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:6082:4: note: ‘snprintf’ output 118 bytes into a destination of size 64
    snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:6157:38: error: ‘%s’ directive output truncated writing 74 bytes into a region of size 58 [-Werror=format-truncation=]
    snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
                                      ^~            ~~~~~~~~
/home/slendl/Projects/gst/gst-sctp/usrsctp/usrsctplib/netinet/sctp_input.c:6157:4: note: ‘snprintf’ output 118 bytes into a destination of size 64
    snprintf(msg, sizeof(msg), "OOTB, %s:%d at %s", __FILE__, __LINE__, __func__);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/usrsctp-static.dir/build.make:111: CMakeFiles/usrsctp-static.dir/netinet/sctp_input.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/usrsctp-static.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by stfl** [comment]
I am trying to build on Manjaro Arch Linux,
Linux stefan-pc 4.10.17-2-MANJARO #1 SMP PREEMPT Sun May 21 11:02:41 UTC 2017 x86_64 GNU/Linux

**Comment by tuexen** [comment]
It is intended the stuff is truncated, but it can be avoided by using https://github.com/sctplab/usrsctp/pull/146, which I'm going to merge soon.

**Comment by tuexen** [comment]
Fixed by https://github.com/sctplab/usrsctp/commit/6cef329951cf0bd771f2f427373f4f160557d469.
